version: '3.8'
services:
  flask-app:
    build: ./flask-app
    restart: unless-stopped
    env_file: ./.env
    environment:
      PORT: 4545
    ports:
      - "4545:4545"
    command: python main.py
  node-app:
    build: ./bezkoder-app
    restart: unless-stopped
    env_file: ./.env
    environment:
      PORT: ${DB_PORT}
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
    command: npm start
  db:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "4502:3306"
volumes:
  db_data:
